#!/usr/bin/env python3
import os
import sys

branch = os.popen('git branch')
for l in branch:
    if (l.startswith('*') and l.split(" ")[1].startswith('hotfix')):
        file = open(sys.argv[1])
        file_content = file.read()
        if (not file_content.startswith('A corregir por:')):
            print('El mensaje debe empezar con `A corregir por:`')
            exit(1) 
